logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    default:
      format: "%(asctime)s %(levelname)5s %(module)s:%(lineno)d [%(threadName)s] %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: default
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: DEBUG
      formatter: default
      filename: logs/ordermatch.log
  loggers:
    defaultLogger:
      level: DEBUG
      handlers: [console, file]
      propagate: no
  root:
    level: DEBUG
    handlers: [console, file]